### ISSUE TITLE
aiohttp errors

### ISSUE THREAD

**Issue by ultra-pool** [eLvErDe/yiimp-blocks-found-to-discord#13]
`Nov 20 18:00:01 dev yiimp-blocks-found-to-discord[4640]: client_session: <aiohttp.client.ClientSession object at 0x7f325c7931d0>
Nov 20 18:00:01 dev yiimp-blocks-found-to-discord[4640]: ERROR    [poll_yiimp_events        ] Exception occurred: AttributeError: __aexit__
Nov 20 18:00:01 dev yiimp-blocks-found-to-discord[4640]: Traceback (most recent call last):
Nov 20 18:00:01 dev yiimp-blocks-found-to-discord[4640]:   File "/usr/local/bin/yiimp-blocks-found-to-discord.py", line 109, in poll_yiimp_events
Nov 20 18:00:01 dev yiimp-blocks-found-to-discord[4640]:     async with aiohttp.ClientSession() as session:
Nov 20 18:00:01 dev yiimp-blocks-found-to-discord[4640]: AttributeError: __aexit__
Nov 20 18:00:06 dev yiimp-blocks-found-to-discord[4640]: ERROR    [asyncio                  ] Unclosed client session
Nov 20 18:00:06 dev yiimp-blocks-found-to-discord[4640]: client_session: <aiohttp.client.ClientSession object at 0x7f325c793198>
Nov 20 18:00:06 dev yiimp-blocks-found-to-discord[4640]: ERROR    [poll_yiimp_events        ] Exception occurred: AttributeError: __aexit__
Nov 20 18:00:06 dev yiimp-blocks-found-to-discord[4640]: Traceback (most recent call last):
Nov 20 18:00:06 dev yiimp-blocks-found-to-discord[4640]:   File "/usr/local/bin/yiimp-blocks-found-to-discord.py", line 109, in poll_yiimp_events
Nov 20 18:00:06 dev yiimp-blocks-found-to-discord[4640]:     async with aiohttp.ClientSession() as session:
Nov 20 18:00:06 dev yiimp-blocks-found-to-discord[4640]: AttributeError: __aexit__`

Anyone have an idea. Iv tried both the newer one and the older thats linked up on the readme

**Comment by eLvErDe** [comment]
You don't have __aexit__ so you're running an old aiohttp version. Use the one that doesn't use "async with"
