### ISSUE TITLE
Multi pool

### ISSUE THREAD

**Issue by mrblackstuff** [eLvErDe/yiimp-blocks-found-to-discord#7]
Hello I am looking to use this to check the POOL_URL of multiple pools and display which pool found a block on discord. Firstly is there a way to do this. Secondly, I guess we would also need to specify a value of say "POOL_NAME" to denote which pool?

**Comment by eLvErDe** [comment]
Hello,

You can run multiple instance of this script for sure but the message does not contain the pool name. Just duplicate the script and edit it to change the content of the message posted to discord API.
